// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAllInstancesWithOrgName = `-- name: ListAllInstancesWithOrgName :many
SELECT instances.id, instances.org_id, instances.slug, instances.name, instances.admin_username, instances.admin_email, instances.status, instances.listmonk_tenant_id, instances.admin_setup_url, instances.created_at, instances.updated_at, orgs.name AS org_name
FROM instances
JOIN orgs ON orgs.id = instances.org_id
ORDER BY instances.created_at DESC
`

type ListAllInstancesWithOrgNameRow struct {
	ID               pgtype.UUID        `json:"id"`
	OrgID            pgtype.UUID        `json:"org_id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	AdminUsername    string             `json:"admin_username"`
	AdminEmail       string             `json:"admin_email"`
	Status           string             `json:"status"`
	ListmonkTenantID *int32             `json:"listmonk_tenant_id"`
	AdminSetupUrl    *string            `json:"admin_setup_url"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	OrgName          string             `json:"org_name"`
}

func (q *Queries) ListAllInstancesWithOrgName(ctx context.Context) ([]ListAllInstancesWithOrgNameRow, error) {
	rows, err := q.db.Query(ctx, listAllInstancesWithOrgName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllInstancesWithOrgNameRow{}
	for rows.Next() {
		var i ListAllInstancesWithOrgNameRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.Name,
			&i.AdminUsername,
			&i.AdminEmail,
			&i.Status,
			&i.ListmonkTenantID,
			&i.AdminSetupUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllOrgsWithInstanceCount = `-- name: ListAllOrgsWithInstanceCount :many

SELECT orgs.id, orgs.name, orgs.listmonk_organization_id, orgs.created_at, orgs.updated_at, COUNT(instances.id) AS instance_count
FROM orgs
LEFT JOIN instances ON instances.org_id = orgs.id
GROUP BY orgs.id
ORDER BY orgs.created_at
`

type ListAllOrgsWithInstanceCountRow struct {
	ID                     pgtype.UUID        `json:"id"`
	Name                   string             `json:"name"`
	ListmonkOrganizationID *int32             `json:"listmonk_organization_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	InstanceCount          int64              `json:"instance_count"`
}

// Cross-org queries for the super-admin surface -- deliberately separate
// from orgs.sql/instances.sql since every query here intentionally skips
// the org-membership scoping every other query enforces.
func (q *Queries) ListAllOrgsWithInstanceCount(ctx context.Context) ([]ListAllOrgsWithInstanceCountRow, error) {
	rows, err := q.db.Query(ctx, listAllOrgsWithInstanceCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllOrgsWithInstanceCountRow{}
	for rows.Next() {
		var i ListAllOrgsWithInstanceCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ListmonkOrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InstanceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
