// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custom_domains.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomDomain = `-- name: CreateCustomDomain :one
INSERT INTO custom_domains (id, instance_id, domain, cloudflare_hostname_id)
VALUES ($1, $2, $3, $4)
RETURNING id, instance_id, domain, cloudflare_hostname_id, status, created_at
`

type CreateCustomDomainParams struct {
	ID                   pgtype.UUID `json:"id"`
	InstanceID           pgtype.UUID `json:"instance_id"`
	Domain               string      `json:"domain"`
	CloudflareHostnameID string      `json:"cloudflare_hostname_id"`
}

func (q *Queries) CreateCustomDomain(ctx context.Context, arg CreateCustomDomainParams) (CustomDomain, error) {
	row := q.db.QueryRow(ctx, createCustomDomain,
		arg.ID,
		arg.InstanceID,
		arg.Domain,
		arg.CloudflareHostnameID,
	)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Domain,
		&i.CloudflareHostnameID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCustomDomainByInstanceID = `-- name: DeleteCustomDomainByInstanceID :exec
DELETE FROM custom_domains WHERE instance_id = $1
`

func (q *Queries) DeleteCustomDomainByInstanceID(ctx context.Context, instanceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCustomDomainByInstanceID, instanceID)
	return err
}

const getCustomDomainByInstanceID = `-- name: GetCustomDomainByInstanceID :one
SELECT id, instance_id, domain, cloudflare_hostname_id, status, created_at FROM custom_domains WHERE instance_id = $1
`

func (q *Queries) GetCustomDomainByInstanceID(ctx context.Context, instanceID pgtype.UUID) (CustomDomain, error) {
	row := q.db.QueryRow(ctx, getCustomDomainByInstanceID, instanceID)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Domain,
		&i.CloudflareHostnameID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const markCustomDomainActive = `-- name: MarkCustomDomainActive :one
UPDATE custom_domains
SET status = 'active'
WHERE id = $1
RETURNING id, instance_id, domain, cloudflare_hostname_id, status, created_at
`

func (q *Queries) MarkCustomDomainActive(ctx context.Context, id pgtype.UUID) (CustomDomain, error) {
	row := q.db.QueryRow(ctx, markCustomDomainActive, id)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Domain,
		&i.CloudflareHostnameID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
