// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dns_records.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDNSRecord = `-- name: CreateDNSRecord :one
INSERT INTO dns_records (id, instance_id, record_type, host, value)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, instance_id, record_type, host, value, verified, created_at
`

type CreateDNSRecordParams struct {
	ID         pgtype.UUID `json:"id"`
	InstanceID pgtype.UUID `json:"instance_id"`
	RecordType string      `json:"record_type"`
	Host       string      `json:"host"`
	Value      string      `json:"value"`
}

func (q *Queries) CreateDNSRecord(ctx context.Context, arg CreateDNSRecordParams) (DnsRecord, error) {
	row := q.db.QueryRow(ctx, createDNSRecord,
		arg.ID,
		arg.InstanceID,
		arg.RecordType,
		arg.Host,
		arg.Value,
	)
	var i DnsRecord
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.RecordType,
		&i.Host,
		&i.Value,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const listDNSRecordsByInstance = `-- name: ListDNSRecordsByInstance :many
SELECT id, instance_id, record_type, host, value, verified, created_at FROM dns_records WHERE instance_id = $1 ORDER BY created_at
`

func (q *Queries) ListDNSRecordsByInstance(ctx context.Context, instanceID pgtype.UUID) ([]DnsRecord, error) {
	rows, err := q.db.Query(ctx, listDNSRecordsByInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsRecord{}
	for rows.Next() {
		var i DnsRecord
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.RecordType,
			&i.Host,
			&i.Value,
			&i.Verified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDNSRecordVerified = `-- name: MarkDNSRecordVerified :one
UPDATE dns_records
SET verified = true
WHERE id = $1
RETURNING id, instance_id, record_type, host, value, verified, created_at
`

func (q *Queries) MarkDNSRecordVerified(ctx context.Context, id pgtype.UUID) (DnsRecord, error) {
	row := q.db.QueryRow(ctx, markDNSRecordVerified, id)
	var i DnsRecord
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.RecordType,
		&i.Host,
		&i.Value,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}
