// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dns_records.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDNSRecord = `-- name: CreateDNSRecord :one
INSERT INTO dns_records (id, instance_id, record_type, host, value)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, instance_id, record_type, host, value, verified, created_at
`

type CreateDNSRecordParams struct {
	ID         pgtype.UUID `json:"id"`
	InstanceID pgtype.UUID `json:"instance_id"`
	RecordType string      `json:"record_type"`
	Host       string      `json:"host"`
	Value      string      `json:"value"`
}

func (q *Queries) CreateDNSRecord(ctx context.Context, arg CreateDNSRecordParams) (DnsRecord, error) {
	row := q.db.QueryRow(ctx, createDNSRecord,
		arg.ID,
		arg.InstanceID,
		arg.RecordType,
		arg.Host,
		arg.Value,
	)
	var i DnsRecord
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.RecordType,
		&i.Host,
		&i.Value,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDNSRecordsByInstanceAndTypes = `-- name: DeleteDNSRecordsByInstanceAndTypes :exec
DELETE FROM dns_records
WHERE instance_id = $1 AND record_type = ANY($2::text[])
`

type DeleteDNSRecordsByInstanceAndTypesParams struct {
	InstanceID  pgtype.UUID `json:"instance_id"`
	RecordTypes []string    `json:"record_types"`
}

func (q *Queries) DeleteDNSRecordsByInstanceAndTypes(ctx context.Context, arg DeleteDNSRecordsByInstanceAndTypesParams) error {
	_, err := q.db.Exec(ctx, deleteDNSRecordsByInstanceAndTypes, arg.InstanceID, arg.RecordTypes)
	return err
}

const listDNSRecordsByInstanceAndTypes = `-- name: ListDNSRecordsByInstanceAndTypes :many
SELECT id, instance_id, record_type, host, value, verified, created_at FROM dns_records
WHERE instance_id = $1 AND record_type = ANY($2::text[])
ORDER BY created_at
`

type ListDNSRecordsByInstanceAndTypesParams struct {
	InstanceID  pgtype.UUID `json:"instance_id"`
	RecordTypes []string    `json:"record_types"`
}

// record_types filters to the caller's own concern -- sender identities
// and custom domains share this table (see docs/custom-domains.md) but
// must never see each other's records.
func (q *Queries) ListDNSRecordsByInstanceAndTypes(ctx context.Context, arg ListDNSRecordsByInstanceAndTypesParams) ([]DnsRecord, error) {
	rows, err := q.db.Query(ctx, listDNSRecordsByInstanceAndTypes, arg.InstanceID, arg.RecordTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsRecord{}
	for rows.Next() {
		var i DnsRecord
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.RecordType,
			&i.Host,
			&i.Value,
			&i.Verified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDNSRecordVerified = `-- name: MarkDNSRecordVerified :one
UPDATE dns_records
SET verified = true
WHERE id = $1
RETURNING id, instance_id, record_type, host, value, verified, created_at
`

func (q *Queries) MarkDNSRecordVerified(ctx context.Context, id pgtype.UUID) (DnsRecord, error) {
	row := q.db.QueryRow(ctx, markDNSRecordVerified, id)
	var i DnsRecord
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.RecordType,
		&i.Host,
		&i.Value,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}
