// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instances.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInstance = `-- name: CreateInstance :one
INSERT INTO instances (id, org_id, slug, name, admin_username, admin_email, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, slug, name, admin_username, admin_email, status, listmonk_tenant_id, admin_setup_url, created_at, updated_at
`

type CreateInstanceParams struct {
	ID            pgtype.UUID `json:"id"`
	OrgID         pgtype.UUID `json:"org_id"`
	Slug          string      `json:"slug"`
	Name          string      `json:"name"`
	AdminUsername string      `json:"admin_username"`
	AdminEmail    string      `json:"admin_email"`
	Status        string      `json:"status"`
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instance, error) {
	row := q.db.QueryRow(ctx, createInstance,
		arg.ID,
		arg.OrgID,
		arg.Slug,
		arg.Name,
		arg.AdminUsername,
		arg.AdminEmail,
		arg.Status,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.AdminUsername,
		&i.AdminEmail,
		&i.Status,
		&i.ListmonkTenantID,
		&i.AdminSetupUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInstance = `-- name: DeleteInstance :exec
DELETE FROM instances WHERE id = $1
`

// Cascades to postmark_servers, dns_records, provisioning_jobs.
func (q *Queries) DeleteInstance(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInstance, id)
	return err
}

const getInstanceByID = `-- name: GetInstanceByID :one
SELECT id, org_id, slug, name, admin_username, admin_email, status, listmonk_tenant_id, admin_setup_url, created_at, updated_at FROM instances WHERE id = $1
`

func (q *Queries) GetInstanceByID(ctx context.Context, id pgtype.UUID) (Instance, error) {
	row := q.db.QueryRow(ctx, getInstanceByID, id)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.AdminUsername,
		&i.AdminEmail,
		&i.Status,
		&i.ListmonkTenantID,
		&i.AdminSetupUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstanceForOrg = `-- name: GetInstanceForOrg :one
SELECT id, org_id, slug, name, admin_username, admin_email, status, listmonk_tenant_id, admin_setup_url, created_at, updated_at FROM instances WHERE id = $1 AND org_id = $2
`

type GetInstanceForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

// Ownership check baked into the query rather than done separately in
// application code, so a wrong instance id and a wrong org fail the same way.
func (q *Queries) GetInstanceForOrg(ctx context.Context, arg GetInstanceForOrgParams) (Instance, error) {
	row := q.db.QueryRow(ctx, getInstanceForOrg, arg.ID, arg.OrgID)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.AdminUsername,
		&i.AdminEmail,
		&i.Status,
		&i.ListmonkTenantID,
		&i.AdminSetupUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInstancesByOrg = `-- name: ListInstancesByOrg :many
SELECT id, org_id, slug, name, admin_username, admin_email, status, listmonk_tenant_id, admin_setup_url, created_at, updated_at FROM instances WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListInstancesByOrg(ctx context.Context, orgID pgtype.UUID) ([]Instance, error) {
	rows, err := q.db.Query(ctx, listInstancesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Instance{}
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.Name,
			&i.AdminUsername,
			&i.AdminEmail,
			&i.Status,
			&i.ListmonkTenantID,
			&i.AdminSetupUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInstanceListmonkTenant = `-- name: SetInstanceListmonkTenant :one
UPDATE instances
SET listmonk_tenant_id = $2, admin_setup_url = $3, updated_at = now()
WHERE id = $1
RETURNING id, org_id, slug, name, admin_username, admin_email, status, listmonk_tenant_id, admin_setup_url, created_at, updated_at
`

type SetInstanceListmonkTenantParams struct {
	ID               pgtype.UUID `json:"id"`
	ListmonkTenantID *int32      `json:"listmonk_tenant_id"`
	AdminSetupUrl    *string     `json:"admin_setup_url"`
}

// Called once provision_listmonk_tenant succeeds: records the fork's tenant
// id and the one-time setup link handed back by POST /api/operator/tenants.
func (q *Queries) SetInstanceListmonkTenant(ctx context.Context, arg SetInstanceListmonkTenantParams) (Instance, error) {
	row := q.db.QueryRow(ctx, setInstanceListmonkTenant, arg.ID, arg.ListmonkTenantID, arg.AdminSetupUrl)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.AdminUsername,
		&i.AdminEmail,
		&i.Status,
		&i.ListmonkTenantID,
		&i.AdminSetupUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInstanceSetupURL = `-- name: UpdateInstanceSetupURL :one
UPDATE instances
SET admin_setup_url = $2, updated_at = now()
WHERE id = $1
RETURNING id, org_id, slug, name, admin_username, admin_email, status, listmonk_tenant_id, admin_setup_url, created_at, updated_at
`

type UpdateInstanceSetupURLParams struct {
	ID            pgtype.UUID `json:"id"`
	AdminSetupUrl *string     `json:"admin_setup_url"`
}

// Backs the dashboard's "resend setup link" action, which calls
// POST /api/operator/tenants/{id}/setup-link and stores the fresh one-time URL.
func (q *Queries) UpdateInstanceSetupURL(ctx context.Context, arg UpdateInstanceSetupURLParams) (Instance, error) {
	row := q.db.QueryRow(ctx, updateInstanceSetupURL, arg.ID, arg.AdminSetupUrl)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.AdminUsername,
		&i.AdminEmail,
		&i.Status,
		&i.ListmonkTenantID,
		&i.AdminSetupUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInstanceStatus = `-- name: UpdateInstanceStatus :one
UPDATE instances
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, org_id, slug, name, admin_username, admin_email, status, listmonk_tenant_id, admin_setup_url, created_at, updated_at
`

type UpdateInstanceStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateInstanceStatus(ctx context.Context, arg UpdateInstanceStatusParams) (Instance, error) {
	row := q.db.QueryRow(ctx, updateInstanceStatus, arg.ID, arg.Status)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.AdminUsername,
		&i.AdminEmail,
		&i.Status,
		&i.ListmonkTenantID,
		&i.AdminSetupUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
