// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CustomDomain struct {
	ID                   pgtype.UUID        `json:"id"`
	InstanceID           pgtype.UUID        `json:"instance_id"`
	Domain               string             `json:"domain"`
	CloudflareHostnameID string             `json:"cloudflare_hostname_id"`
	Status               string             `json:"status"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type DnsRecord struct {
	ID         pgtype.UUID        `json:"id"`
	InstanceID pgtype.UUID        `json:"instance_id"`
	RecordType string             `json:"record_type"`
	Host       string             `json:"host"`
	Value      string             `json:"value"`
	Verified   bool               `json:"verified"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Instance struct {
	ID               pgtype.UUID        `json:"id"`
	OrgID            pgtype.UUID        `json:"org_id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	AdminUsername    string             `json:"admin_username"`
	AdminEmail       string             `json:"admin_email"`
	Status           string             `json:"status"`
	ListmonkTenantID *int32             `json:"listmonk_tenant_id"`
	AdminSetupUrl    *string            `json:"admin_setup_url"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Org struct {
	ID                     pgtype.UUID        `json:"id"`
	Name                   string             `json:"name"`
	ListmonkOrganizationID *int32             `json:"listmonk_organization_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type OrgMember struct {
	OrgID     pgtype.UUID        `json:"org_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PostmarkServer struct {
	ID                pgtype.UUID        `json:"id"`
	InstanceID        pgtype.UUID        `json:"instance_id"`
	PostmarkServerID  string             `json:"postmark_server_id"`
	ApiTokenEncrypted string             `json:"api_token_encrypted"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ProvisioningJob struct {
	ID         pgtype.UUID        `json:"id"`
	InstanceID pgtype.UUID        `json:"instance_id"`
	JobType    string             `json:"job_type"`
	Status     string             `json:"status"`
	Attempts   int32              `json:"attempts"`
	LastError  *string            `json:"last_error"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type SenderIdentity struct {
	ID         pgtype.UUID        `json:"id"`
	InstanceID pgtype.UUID        `json:"instance_id"`
	Kind       string             `json:"kind"`
	Value      string             `json:"value"`
	PostmarkID string             `json:"postmark_id"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	ZitadelSubject string             `json:"zitadel_subject"`
	Email          string             `json:"email"`
	DisplayName    *string            `json:"display_name"`
	IsSuperAdmin   bool               `json:"is_super_admin"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
