// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: org_members.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOrgMember = `-- name: AddOrgMember :one
INSERT INTO org_members (org_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING org_id, user_id, role, created_at
`

type AddOrgMemberParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) AddOrgMember(ctx context.Context, arg AddOrgMemberParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, addOrgMember, arg.OrgID, arg.UserID, arg.Role)
	var i OrgMember
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgMember = `-- name: GetOrgMember :one
SELECT org_id, user_id, role, created_at FROM org_members WHERE org_id = $1 AND user_id = $2
`

type GetOrgMemberParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Authorization check: is this user a member of this org, and with what role.
func (q *Queries) GetOrgMember(ctx context.Context, arg GetOrgMemberParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, getOrgMember, arg.OrgID, arg.UserID)
	var i OrgMember
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listOrgMembers = `-- name: ListOrgMembers :many
SELECT org_id, user_id, role, created_at FROM org_members WHERE org_id = $1 ORDER BY created_at
`

func (q *Queries) ListOrgMembers(ctx context.Context, orgID pgtype.UUID) ([]OrgMember, error) {
	rows, err := q.db.Query(ctx, listOrgMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrgMember{}
	for rows.Next() {
		var i OrgMember
		if err := rows.Scan(
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
