// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrg = `-- name: CreateOrg :one
INSERT INTO orgs (id, name, listmonk_organization_id)
VALUES ($1, $2, $3)
RETURNING id, name, listmonk_organization_id, created_at, updated_at
`

type CreateOrgParams struct {
	ID                     pgtype.UUID `json:"id"`
	Name                   string      `json:"name"`
	ListmonkOrganizationID *int32      `json:"listmonk_organization_id"`
}

// The listmonk Organization is created first (see internal/provisioning),
// so its id is always known by the time this row is written -- there's no
// "org exists locally without its listmonk twin" state to reconcile.
func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, createOrg, arg.ID, arg.Name, arg.ListmonkOrganizationID)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ListmonkOrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgByID = `-- name: GetOrgByID :one
SELECT id, name, listmonk_organization_id, created_at, updated_at FROM orgs WHERE id = $1
`

func (q *Queries) GetOrgByID(ctx context.Context, id pgtype.UUID) (Org, error) {
	row := q.db.QueryRow(ctx, getOrgByID, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ListmonkOrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrgsByUser = `-- name: ListOrgsByUser :many
SELECT orgs.id, orgs.name, orgs.listmonk_organization_id, orgs.created_at, orgs.updated_at, org_members.role FROM orgs
JOIN org_members ON org_members.org_id = orgs.id
WHERE org_members.user_id = $1
ORDER BY orgs.created_at
`

type ListOrgsByUserRow struct {
	ID                     pgtype.UUID        `json:"id"`
	Name                   string             `json:"name"`
	ListmonkOrganizationID *int32             `json:"listmonk_organization_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	Role                   string             `json:"role"`
}

// org_members.role is the caller's own role in each org -- lets the
// frontend gate owner-only actions (e.g. inviting members) without a
// second round trip per org.
func (q *Queries) ListOrgsByUser(ctx context.Context, userID pgtype.UUID) ([]ListOrgsByUserRow, error) {
	rows, err := q.db.Query(ctx, listOrgsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgsByUserRow{}
	for rows.Next() {
		var i ListOrgsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ListmonkOrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
