// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: postmark_servers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPostmarkServer = `-- name: CreatePostmarkServer :one
INSERT INTO postmark_servers (id, instance_id, postmark_server_id, api_token_encrypted)
VALUES ($1, $2, $3, $4)
RETURNING id, instance_id, postmark_server_id, api_token_encrypted, created_at
`

type CreatePostmarkServerParams struct {
	ID                pgtype.UUID `json:"id"`
	InstanceID        pgtype.UUID `json:"instance_id"`
	PostmarkServerID  string      `json:"postmark_server_id"`
	ApiTokenEncrypted string      `json:"api_token_encrypted"`
}

func (q *Queries) CreatePostmarkServer(ctx context.Context, arg CreatePostmarkServerParams) (PostmarkServer, error) {
	row := q.db.QueryRow(ctx, createPostmarkServer,
		arg.ID,
		arg.InstanceID,
		arg.PostmarkServerID,
		arg.ApiTokenEncrypted,
	)
	var i PostmarkServer
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.PostmarkServerID,
		&i.ApiTokenEncrypted,
		&i.CreatedAt,
	)
	return i, err
}

const getPostmarkServerByInstanceID = `-- name: GetPostmarkServerByInstanceID :one
SELECT id, instance_id, postmark_server_id, api_token_encrypted, created_at FROM postmark_servers WHERE instance_id = $1
`

func (q *Queries) GetPostmarkServerByInstanceID(ctx context.Context, instanceID pgtype.UUID) (PostmarkServer, error) {
	row := q.db.QueryRow(ctx, getPostmarkServerByInstanceID, instanceID)
	var i PostmarkServer
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.PostmarkServerID,
		&i.ApiTokenEncrypted,
		&i.CreatedAt,
	)
	return i, err
}
