// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provisioning_jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProvisioningJob = `-- name: CreateProvisioningJob :one
INSERT INTO provisioning_jobs (id, instance_id, job_type, status)
VALUES ($1, $2, $3, 'pending')
RETURNING id, instance_id, job_type, status, attempts, last_error, created_at, updated_at
`

type CreateProvisioningJobParams struct {
	ID         pgtype.UUID `json:"id"`
	InstanceID pgtype.UUID `json:"instance_id"`
	JobType    string      `json:"job_type"`
}

func (q *Queries) CreateProvisioningJob(ctx context.Context, arg CreateProvisioningJobParams) (ProvisioningJob, error) {
	row := q.db.QueryRow(ctx, createProvisioningJob, arg.ID, arg.InstanceID, arg.JobType)
	var i ProvisioningJob
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.JobType,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProvisioningJobsByInstance = `-- name: ListProvisioningJobsByInstance :many
SELECT id, instance_id, job_type, status, attempts, last_error, created_at, updated_at FROM provisioning_jobs WHERE instance_id = $1 ORDER BY created_at
`

// Backs GET /instances/{id}/events -- the provisioning timeline shown in the UI.
func (q *Queries) ListProvisioningJobsByInstance(ctx context.Context, instanceID pgtype.UUID) ([]ProvisioningJob, error) {
	rows, err := q.db.Query(ctx, listProvisioningJobsByInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProvisioningJob{}
	for rows.Next() {
		var i ProvisioningJob
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.JobType,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvisioningJobStatus = `-- name: UpdateProvisioningJobStatus :one
UPDATE provisioning_jobs
SET status = $2, attempts = attempts + 1, last_error = $3, updated_at = now()
WHERE id = $1
RETURNING id, instance_id, job_type, status, attempts, last_error, created_at, updated_at
`

type UpdateProvisioningJobStatusParams struct {
	ID        pgtype.UUID `json:"id"`
	Status    string      `json:"status"`
	LastError *string     `json:"last_error"`
}

func (q *Queries) UpdateProvisioningJobStatus(ctx context.Context, arg UpdateProvisioningJobStatusParams) (ProvisioningJob, error) {
	row := q.db.QueryRow(ctx, updateProvisioningJobStatus, arg.ID, arg.Status, arg.LastError)
	var i ProvisioningJob
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.JobType,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
