// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddOrgMember(ctx context.Context, arg AddOrgMemberParams) (OrgMember, error)
	CreateDNSRecord(ctx context.Context, arg CreateDNSRecordParams) (DnsRecord, error)
	CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instance, error)
	// The listmonk Organization is created first (see internal/provisioning),
	// so its id is always known by the time this row is written -- there's no
	// "org exists locally without its listmonk twin" state to reconcile.
	CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error)
	CreatePostmarkServer(ctx context.Context, arg CreatePostmarkServerParams) (PostmarkServer, error)
	CreateProvisioningJob(ctx context.Context, arg CreateProvisioningJobParams) (ProvisioningJob, error)
	CreateSenderIdentity(ctx context.Context, arg CreateSenderIdentityParams) (SenderIdentity, error)
	// JIT provisioning: called the first time we see a valid Zitadel token for a
	// subject we don't have a row for yet.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteDNSRecordsByInstance(ctx context.Context, instanceID pgtype.UUID) error
	// Cascades to postmark_servers, dns_records, provisioning_jobs.
	DeleteInstance(ctx context.Context, id pgtype.UUID) error
	DeletePostmarkServerByInstanceID(ctx context.Context, instanceID pgtype.UUID) error
	DeleteSenderIdentityByInstanceID(ctx context.Context, instanceID pgtype.UUID) error
	GetInstanceByID(ctx context.Context, id pgtype.UUID) (Instance, error)
	// Ownership check baked into the query rather than done separately in
	// application code, so a wrong instance id and a wrong org fail the same way.
	GetInstanceForOrg(ctx context.Context, arg GetInstanceForOrgParams) (Instance, error)
	GetOrgByID(ctx context.Context, id pgtype.UUID) (Org, error)
	// Authorization check: is this user a member of this org, and with what role.
	GetOrgMember(ctx context.Context, arg GetOrgMemberParams) (OrgMember, error)
	GetPostmarkServerByInstanceID(ctx context.Context, instanceID pgtype.UUID) (PostmarkServer, error)
	GetSenderIdentityByInstanceID(ctx context.Context, instanceID pgtype.UUID) (SenderIdentity, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	// Looked up on every authenticated request after the OIDC middleware verifies
	// the bearer token; a miss here means first login, so the caller JIT-provisions
	// via CreateUser.
	GetUserByZitadelSubject(ctx context.Context, zitadelSubject string) (User, error)
	ListAllInstancesWithOrgName(ctx context.Context) ([]ListAllInstancesWithOrgNameRow, error)
	// Cross-org queries for the super-admin surface -- deliberately separate
	// from orgs.sql/instances.sql since every query here intentionally skips
	// the org-membership scoping every other query enforces.
	ListAllOrgsWithInstanceCount(ctx context.Context) ([]ListAllOrgsWithInstanceCountRow, error)
	ListDNSRecordsByInstance(ctx context.Context, instanceID pgtype.UUID) ([]DnsRecord, error)
	ListInstancesByOrg(ctx context.Context, orgID pgtype.UUID) ([]Instance, error)
	ListOrgMembers(ctx context.Context, orgID pgtype.UUID) ([]OrgMember, error)
	// Backs the dashboard's members page: needs email/display_name, which
	// org_members alone doesn't carry.
	ListOrgMembersWithUser(ctx context.Context, orgID pgtype.UUID) ([]ListOrgMembersWithUserRow, error)
	ListOrgsByUser(ctx context.Context, userID pgtype.UUID) ([]Org, error)
	// Backs GET /instances/{id}/events -- the provisioning timeline shown in the UI.
	ListProvisioningJobsByInstance(ctx context.Context, instanceID pgtype.UUID) ([]ProvisioningJob, error)
	MarkDNSRecordVerified(ctx context.Context, id pgtype.UUID) (DnsRecord, error)
	MarkSenderIdentityConfirmed(ctx context.Context, id pgtype.UUID) (SenderIdentity, error)
	// Called once provision_listmonk_tenant succeeds: records the fork's tenant
	// id and the one-time setup link handed back by POST /api/operator/tenants.
	SetInstanceListmonkTenant(ctx context.Context, arg SetInstanceListmonkTenantParams) (Instance, error)
	// Backs cmd/promote-admin -- the only way to grant is_super_admin, by
	// deliberate design (see the column's doc comment in the init migration).
	SetUserSuperAdmin(ctx context.Context, arg SetUserSuperAdminParams) (User, error)
	// Backs the dashboard's "resend setup link" action, which calls
	// POST /api/operator/tenants/{id}/setup-link and stores the fresh one-time URL.
	UpdateInstanceSetupURL(ctx context.Context, arg UpdateInstanceSetupURLParams) (Instance, error)
	UpdateInstanceStatus(ctx context.Context, arg UpdateInstanceStatusParams) (Instance, error)
	UpdateProvisioningJobStatus(ctx context.Context, arg UpdateProvisioningJobStatusParams) (ProvisioningJob, error)
	// Keeps email/display_name in sync if they change on the Zitadel side.
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
