// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sender_identities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSenderIdentity = `-- name: CreateSenderIdentity :one
INSERT INTO sender_identities (id, instance_id, kind, value, postmark_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, instance_id, kind, value, postmark_id, status, created_at
`

type CreateSenderIdentityParams struct {
	ID         pgtype.UUID `json:"id"`
	InstanceID pgtype.UUID `json:"instance_id"`
	Kind       string      `json:"kind"`
	Value      string      `json:"value"`
	PostmarkID string      `json:"postmark_id"`
}

func (q *Queries) CreateSenderIdentity(ctx context.Context, arg CreateSenderIdentityParams) (SenderIdentity, error) {
	row := q.db.QueryRow(ctx, createSenderIdentity,
		arg.ID,
		arg.InstanceID,
		arg.Kind,
		arg.Value,
		arg.PostmarkID,
	)
	var i SenderIdentity
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Kind,
		&i.Value,
		&i.PostmarkID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getSenderIdentityByInstanceID = `-- name: GetSenderIdentityByInstanceID :one
SELECT id, instance_id, kind, value, postmark_id, status, created_at FROM sender_identities WHERE instance_id = $1
`

func (q *Queries) GetSenderIdentityByInstanceID(ctx context.Context, instanceID pgtype.UUID) (SenderIdentity, error) {
	row := q.db.QueryRow(ctx, getSenderIdentityByInstanceID, instanceID)
	var i SenderIdentity
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Kind,
		&i.Value,
		&i.PostmarkID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const markSenderIdentityConfirmed = `-- name: MarkSenderIdentityConfirmed :one
UPDATE sender_identities
SET status = 'confirmed'
WHERE id = $1
RETURNING id, instance_id, kind, value, postmark_id, status, created_at
`

func (q *Queries) MarkSenderIdentityConfirmed(ctx context.Context, id pgtype.UUID) (SenderIdentity, error) {
	row := q.db.QueryRow(ctx, markSenderIdentityConfirmed, id)
	var i SenderIdentity
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Kind,
		&i.Value,
		&i.PostmarkID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
