// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, zitadel_subject, email, display_name)
VALUES ($1, $2, $3, $4)
RETURNING id, zitadel_subject, email, display_name, is_super_admin, created_at, updated_at
`

type CreateUserParams struct {
	ID             pgtype.UUID `json:"id"`
	ZitadelSubject string      `json:"zitadel_subject"`
	Email          string      `json:"email"`
	DisplayName    *string     `json:"display_name"`
}

// JIT provisioning: called the first time we see a valid Zitadel token for a
// subject we don't have a row for yet.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.ZitadelSubject,
		arg.Email,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelSubject,
		&i.Email,
		&i.DisplayName,
		&i.IsSuperAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, zitadel_subject, email, display_name, is_super_admin, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelSubject,
		&i.Email,
		&i.DisplayName,
		&i.IsSuperAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByZitadelSubject = `-- name: GetUserByZitadelSubject :one
SELECT id, zitadel_subject, email, display_name, is_super_admin, created_at, updated_at FROM users WHERE zitadel_subject = $1
`

// Looked up on every authenticated request after the OIDC middleware verifies
// the bearer token; a miss here means first login, so the caller JIT-provisions
// via CreateUser.
func (q *Queries) GetUserByZitadelSubject(ctx context.Context, zitadelSubject string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByZitadelSubject, zitadelSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelSubject,
		&i.Email,
		&i.DisplayName,
		&i.IsSuperAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET email = $2, display_name = $3, updated_at = now()
WHERE id = $1
RETURNING id, zitadel_subject, email, display_name, is_super_admin, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	Email       string      `json:"email"`
	DisplayName *string     `json:"display_name"`
}

// Keeps email/display_name in sync if they change on the Zitadel side.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelSubject,
		&i.Email,
		&i.DisplayName,
		&i.IsSuperAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
